export const GET_INCIDENTS = 'GET_INCIDENTS';
export const ADD_INCIDENT_TO_SELECTED = 'ADD_INCIDENT_TO_SELECTED';
export const REMOVE_INCIDENT_FROM_SELECTED = 'REMOVE_INCIDENT_FROM_SELECTED';
export const GET_VIEW_PORT = 'GET_VIEW_PORT';
export const CHANGE_VIEW_PORT = 'CHANGE_VIEW_PORT';
